# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.Trips')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.Users')),
            ],
        ),
    ]
