# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_joins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joins',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='joins',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Joins',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
